Screen('Preference', 'Verbosity', 1);
Screen('Preference', 'SkipSyncTests', 1);
win = PsychWindow('screen', 0,...
                  'color', [25 25 25],...
                  'rect', [20 20 350 400]);

img = imread('tests/kitten.png');

imgmat = Image;
imgmat.Add(1, 'original_matrix', img, ...
           'rel_x_pos', 0.5, ...
           'rel_y_pos', 0.5, ...
           'rel_x_scale', 0.2, ...
           'rel_y_scale', 0.2);
       
imgmat.Register(win.pointer);
imgmat.Prime();

imgmat.Draw(1);

win.Flip();

imgmat.Add(2, 'original_matrix', img, ...
           'rel_x_pos', 0.2, ...
           'rel_y_pos', 0.2, ...
           'rel_x_scale', 0.3, ...
           'modulate_color', [20 255 20 100]);
imgmat.Prime();
t0 = GetSecs;
imgmat.Draw(1:2);
disp(GetSecs - t0);
win.Flip();