

draw_settings = struct('source_rect', [], ...
                       'rect', [], ...
                       'rotation_angle', 0, ...
                       'filter_mode', 0, ...% -3 to 5
                       'alpha', 1, ...
                       'modulate_color', [], ...
                       'texture_shader', [], ...
                       'special_flags', [], ...
                       'aux_parameters', []);

self.struct_proto = struct('pointer', [], 'window_index', [], ...
                              'original_matrix', [], ...
                              'optimize_for_draw_angle', 0, ...
                              'special_flags', 0, ...
                              'float_precision', 0, ...
                              'texture_orientation', 0, ...
                              'texture_shader', 0, ...
                              'draw_settings', draw_settings);
self.struct_array = self.struct_proto;
