% sampling_freq * max_line * time_buffer determines the input buffer size
srl = PsychSerial('port', '/dev/ttyACM0',...
                  'sampling_freq', 200,...
                  'max_line', 16,...
                  'time_buffer', 20);

srl.Set('terminator', 13);
