scrn = PsychWindow(0, true,...
                   'color', [255 255 255],...
                   'rect', [50 50 450 450]);

txt = PsychText('val', 'testing testing 123',...
                'style', 'normal',...
                'size',  50, ...
                'color', [0 255 0],...
                'x', 100, 'y', 100);

txt.Draw(scrn.pointer);

scrn.Flip;

KbWait;
scrn.Close;
